services:
  - type: web
    name: quantum-voting-backend
    env: python
    pythonVersion: "3.11"
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
